version: "3"
services:
  poli-reservation:
    image: jotacor/poli-reservation:latest
    container_name: poli-reservation
    network_mode: bridge  
    restart: always
    environment:
    - DEBUG=False
    - HOME="https://website/Home"
    - LOGIN="https://website/Login"
    - SPORT="Sport"
    - WEEKDAY="Viernes"
    - TIME="11"
    - USERNAME="username"
    - PASSWORD="password"
    - EMAIL="email"
    - CREDIT_NUMBER="1234567890123456"
    - CREDIT_EXPIRATION="01/70"
    - CREDIT_CVC="123"